### ISSUE TITLE
Error: image library/hdfs-namenode not found

### ISSUE THREAD

**Issue by shujamughal** [vkorukanti/spark-docker-compose#2]
Hi

I have pulled all the images from docker huba and nex I am running docker-compose up -d command to start the cluster but it showing following error.

 docker-compose up -d
Pulling hdfs-namenode (hdfs-namenode:latest)...
Pulling repository docker.io/library/hdfs-namenode
ERROR: Error: image library/hdfs-namenode not found

what is the problem here?

**Comment by vkorukanti** [comment]
Did you build the images?

**Comment by shujamughal** [comment]
yes, 

here is compelete output.

...
Step 1 : FROM hadoop-spark
Pulling repository docker.io/library/hadoop-spark
Error: image library/hadoop-spark not found
Sending build context to Docker daemon 3.584 kB
Step 1 : FROM hadoop-spark
Pulling repository docker.io/library/hadoop-spark
Error: image library/hadoop-spark not found
Sending build context to Docker daemon 3.584 kB
Step 1 : FROM hadoop-spark
Pulling repository docker.io/library/hadoop-spark
Error: image library/hadoop-spark not found
Sending build context to Docker daemon 3.584 kB
Step 1 : FROM hadoop-spark
Pulling repository docker.io/library/hadoop-spark
Error: image library/hadoop-spark not found

**Comment by shujamughal** [comment]
Hi i have solved the problem, I need to use scratch as cmd line argument to make it work.

Thanks
Shuja

**Comment by vkorukanti** [comment]
Do you want to submit a pull request to update the doc?
